import Image from 'next/image';
import React from 'react';
import styles from 'styles/Layout.module.css'
import Head from 'next/head';

const Layout = ({children, title}) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='grid place-content-center h-screen bg-blue-400'>
                
                <div className='bg-slate-50 rounded-md overflow-hidden min-h-[450px] grid sm:grid-cols-2 sm:grid-rows-1 grid-rows-3 shadow-2xl'>
                    
                    <div className={styles.imgStyle}>
                        <div className='h-full flex flex-col items-center place-content-center justify-center'>
                            <div>
                                <Image src={'/assets/layout.png'} width={400} height={400} alt={'Imagen del Layout'} priority={true}/>
                            </div>
                        </div>
                    </div>

                    <div className='flex flex-col place-content-center sm:col-span-1 row-span-2'>
                        <div className='text-center relative '>
                            {children}
                        </div>
                    </div>
                </div>

            </div>
        </>
    );
}

export default Layout;
