import Image from 'next/image';
import React from 'react';
import styles from 'styles/Layout.module.css'
import Head from 'next/head';

const Layout = ({children, title}) => {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className=' flex flex-col justify-center items-center h-screen bg-blue-400 p-3'>
                
                {/* Contenedor */}
                <div className=' neumorphismoLogin rounded-md overflow-hidden min-w-[50%] min-h-[50%]'>
                    
                    {/* Imagen */}
                    <div className="bg-gradient-to-r from-blue-500 to-indigo-500 rounded-l-md flex flex-col justify-center items-center w-[auto] relative min-h-[200px]">
                        <Image src={'/assets/layout.png'} layout="fill" objectFit='contain' alt="Distrinova" priority={true} className='p-4'/>
                    </div>

                    {/* Login y Register */}
                    <div className='flex flex-col place-content-start sm:place-content-center sm:col-span-1 row-span-2 overflow-y-auto'>
                        <div className='text-center relative mt-2 sm:mt-1 '>
                            {children}
                        </div>
                    </div>
                </div>

            </div>
        </>
    );
}

export default Layout;
