import Head from 'next/head'
import { getSession } from 'next-auth/react'
import MenuPaginas from 'components/menu/menuPaginas'
import Banner from 'components/banner/banner'
import Rubro from 'components/rubros/index'

export default function Home({ session }) {

  const { user } = session

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MenuPaginas user={user}>

        <Banner />

        <Rubro/>

      </MenuPaginas>
    </div>

  )


}

export async function getServerSideProps(context) {

  const session = await getSession(context)

  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: false
      }
    }
  }

  if (session?.error) {
    console.log(session.error)
  }

  console.log(session)

  return {
    props: { session }
  }
}
